# Generated by Django 2.2.24 on 2021-08-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test2',
        ),
    ]
